title: Personal Blog of Michael Cowan
email: mike@mcowan.io
description: >-
  
baseurl: ""
url: "https://blog.mcowan.io"
github_username:  michaelcowan

remote_theme: songzivong/dark-minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme

permalink: /:title:output_ext
