title: Personal Blog of Michael Cowan
email: mike@mcowan.io
description: >-
  
baseurl: ""
url: "https://blog.mcowan.io"
github_username:  michaelcowan

theme: minima
plugins:
  - jekyll-feed

permalink: /:title:output_ext
